name: CI/CD for ticket_booking (docker based)

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

env:
  CONTAINER_NAME: ticket_booking
  IMAGE_NAME: ticket_booking
  NETWORK_NAME: ticket-network


jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Spring Boot
      run: ./gradlew clean build -x test

    - name: Stop & remove container if exists
      run: |
        if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
          docker rm -f $CONTAINER_NAME
        fi

    - name: Remove image if exists
      run: |
        if [ "$(docker images -q $IMAGE_NAME)" ]; then
          docker rmi -f $IMAGE_NAME
        fi

    - name: Build the Docker image
      run: docker buildx build --load -t $IMAGE_NAME -f docker/Dockerfile .

    - name: Run Docker Container
      run: docker run -d --name $CONTAINER_NAME --env-file docker/config.env --network $NETWORK_NAME -p 8080:8080 $IMAGE_NAME
