name: CI/CD for ticket_booking (docker based)

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Spring Boot
      run: ./gradlew clean build -x test

    - name: Build the Docker image
      run: docker buildx build --load -t ticket -f docker/Dockerfile .

    - name: Run Docker Container
      run: docker run -d --name ticket_booking --env-file docker/config.env --network ticket-network -p 8080:8080 ticket
